spring:
    datasource:
        druid:
            url: jdbc:mysql://192.168.1.133:3306/restaurant?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: 123456
            initial-size: 1
            min-idle: 1
            max-active: 20
            test-on-borrow: true
            # MySQL 8.x: com.mysql.cj.jdbc.Driver
            driver-class-name: com.mysql.jdbc.Driver

server:
    port: 9090

mybatis:
    type-aliases-package: com.adgwr.online.ordering.system.domain
    mapper-locations: classpath:mapper/*.xml